imports:
    - { resource: config.yml }
    - { resource: "@UsersUserManageBundle/Resources/config/services.xml" }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false
    position: bottom

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

assetic:
    use_controller: true

parameters:
    records_on_page: 15
    offset: 0
    reseller_user_type: 2
    bg_color:   f3f1f1
    font_color: 434445
    font_size:  14px
    

services:
    usermanage_service: 
        class:      Users\UserManageBundle\DependencyInjection\UsermanageService
        arguments:  [@doctrine.orm.entity_manager, %records_on_page%, %offset% ,%reseller_user_type% ,%bg_color%, %font_color%, %font_size% ]		
#swiftmailer:
#    delivery_address: me@example.com
