<?php

namespace Users\usermanageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * accounttypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class accounttypeRepository extends EntityRepository
{
}
