<?php

namespace Users\UserManageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * permissionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class permissionsRepository extends EntityRepository
{
   public function save_permissions( $user_permissions, $userid ){
	        $permissions = new permissions(); 
	        $entity_manager = $this->getEntityManager(); //access entity manager from inside the repository
	 // Fill the entity
              $permissions->setPermission($user_permissions);
              $permissions->setUserType(2);
              $permissions->setuserId( $userid );              
              $entity_manager->persist( $permissions ); 
              $entity_manager->flush();
    }
	
	
	  public function get_permissions( $userid, $usertype ){
	              $entity_manager = $this->getEntityManager(); //access entity manager from inside the repository
	              $query = $entity_manager->createQuery(  'SELECT p FROM UsersUserManageBundle:permissions p 
                                                       WHERE
                                                       p.userId = :userid 
                                                       AND
                                                       p.userType = :usertype'
                                                    );
              ## Setting parameters to search                                    
              $query->setParameters( array( 'userid'   =>  $userid,
                                            'usertype' =>  $usertype,
                                          )
                                    ); 								
               return $query->getArrayResult( ); //array of users objects
			  
      }
    
  public function update_permissions( $user_permissions, $userid ) {
      $entity_manager = $this->getEntityManager(); //access entity manager from inside the repository
      $query = $entity_manager->createQueryBuilder()
                                    ->update('UsersUserManageBundle:permissions', 'p')
                                    ->set('p.permission', ':permission')
                                    ->where('p.userId = ?1')
                                    ->andwhere('p.userType = ?2')
                                    ->setParameter('permission', $user_permissions)
                                    ->setParameter(1, $userid)
                                    ->setParameter(2, '2')
                                    ->getQuery()->execute();
  }  
}
