<?php

namespace Users\usermanageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * resellerlogoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class resellerlogoRepository extends EntityRepository
{
}
