<?php

namespace Users\UserManageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * stateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class stateRepository extends EntityRepository
{

 
       /*
            state_list() is used to get state list form database
                 
            @params : N/A
            
            @return : array
        */
      public function state_list(){
              $entity_manager = $this->getEntityManager(); //access entity manager from inside the repository
          try{
              $query = $entity_manager->createQuery('SELECT s.name FROM UsersUserManageBundle:state s ');
              return $query->getArrayResult( ); // array of state objects
              throw new \Exception( 'Database error in :: _state_list() function in UsermanageController' );
          }catch( \Exception $e ){
          
          }
      }
	  
}
