<?php

namespace Proxies\__CG__\Users\UserManageBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class signature extends \Users\UserManageBundle\Entity\signature implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Users\\UserManageBundle\\Entity\\signature' . "\0" . 'id', '' . "\0" . 'Users\\UserManageBundle\\Entity\\signature' . "\0" . 'accountId', '' . "\0" . 'Users\\UserManageBundle\\Entity\\signature' . "\0" . 'signature', '' . "\0" . 'Users\\UserManageBundle\\Entity\\signature' . "\0" . 'userType', '' . "\0" . 'Users\\UserManageBundle\\Entity\\signature' . "\0" . 'createdBy', '' . "\0" . 'Users\\UserManageBundle\\Entity\\signature' . "\0" . 'createdAt', '' . "\0" . 'Users\\UserManageBundle\\Entity\\signature' . "\0" . 'modifiedAt', '' . "\0" . 'Users\\UserManageBundle\\Entity\\signature' . "\0" . 'signatureTitle', '' . "\0" . 'Users\\UserManageBundle\\Entity\\signature' . "\0" . 'signatureStatus');
        }

        return array('__isInitialized__', '' . "\0" . 'Users\\UserManageBundle\\Entity\\signature' . "\0" . 'id', '' . "\0" . 'Users\\UserManageBundle\\Entity\\signature' . "\0" . 'accountId', '' . "\0" . 'Users\\UserManageBundle\\Entity\\signature' . "\0" . 'signature', '' . "\0" . 'Users\\UserManageBundle\\Entity\\signature' . "\0" . 'userType', '' . "\0" . 'Users\\UserManageBundle\\Entity\\signature' . "\0" . 'createdBy', '' . "\0" . 'Users\\UserManageBundle\\Entity\\signature' . "\0" . 'createdAt', '' . "\0" . 'Users\\UserManageBundle\\Entity\\signature' . "\0" . 'modifiedAt', '' . "\0" . 'Users\\UserManageBundle\\Entity\\signature' . "\0" . 'signatureTitle', '' . "\0" . 'Users\\UserManageBundle\\Entity\\signature' . "\0" . 'signatureStatus');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (signature $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setAccountId($accountId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccountId', array($accountId));

        return parent::setAccountId($accountId);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccountId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccountId', array());

        return parent::getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSignature($signature)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSignature', array($signature));

        return parent::setSignature($signature);
    }

    /**
     * {@inheritDoc}
     */
    public function getSignature()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSignature', array());

        return parent::getSignature();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserType($userType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserType', array($userType));

        return parent::setUserType($userType);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserType', array());

        return parent::getUserType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($createdBy));

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedAt($modifiedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedAt', array($modifiedAt));

        return parent::setModifiedAt($modifiedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedAt', array());

        return parent::getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setSignatureTitle($signatureTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSignatureTitle', array($signatureTitle));

        return parent::setSignatureTitle($signatureTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getSignatureTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSignatureTitle', array());

        return parent::getSignatureTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setSignatureStatus($signatureStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSignatureStatus', array($signatureStatus));

        return parent::setSignatureStatus($signatureStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getSignatureStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSignatureStatus', array());

        return parent::getSignatureStatus();
    }

}
